import Head from "next/head";
import styles from "../styles/Home.module.css";
import { NextPage } from "next";
import Button from "@mui/material/Button";
import SendIcon from "@mui/icons-material/Message";
import { makeStyles } from "@mui/styles";
import { styleTheme } from "./theme";
import Navbar from "../components/Navbar";
import Leftbar from "../components/Leftbar";
import { Grid } from "@mui/material";
import Feed from "../components/Feed";
import Rightbar from "../components/Rightbar"
import Add from "../components/Add";

const useStyles = makeStyles((theme: any) => ({
  button: {
    // @ts-ignore
    ...styleTheme.myButton,
  },
  right: {
    [theme.breakpoints.down("sm")]: {
      marginBottom: theme.spacing(3),
      cursor: "pointer",
    },
  },
}));

const Home: NextPage = () => {
  const classes = useStyles();

  return (
    <div>
      <Head>
        <title>Create Next App with Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Grid container>
          <Grid item sm={2} xs={2}>
            <Leftbar />
          </Grid>
          <Grid item sm={7} xs={10}>
            <Feed/>
          </Grid>
          <Grid item sm={3} className={classes.right}>
            <Rightbar/>
          </Grid>
        </Grid>
        <Add/>
      </main>
    </div>
  );
};
export default Home;
