import Head from "next/head";
import styles from "../styles/Home.module.css";
import { NextPage } from "next";
import Button from "@mui/material/Button";
import SendIcon from "@mui/icons-material/Message";
import { makeStyles } from "@mui/styles";
import { styleTheme } from "./theme";
import Navbar from "../components/Navbar";
import Leftbar from "../components/Leftbar";

const useStyles = makeStyles((theme) => ({
  button: {
    // @ts-ignore
    ...styleTheme.myButton,
  },
}));

const Home: NextPage = () => {
  const classes = useStyles();

  return (
    <div>
      <Head>
        <title>Create Next App with Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Leftbar/>
    </div>
  );
};
export default Home;
