import Head from "next/head";
import styles from "../styles/Home.module.css";
import { NextPage } from "next";
import Button from "@mui/material/Button";
import SendIcon from "@mui/icons-material/Message";
import { makeStyles } from "@mui/styles";
import { styleTheme } from "../../pages/theme";

const useStyles = makeStyles((theme) => ({
  button: {
    // @ts-ignore
    ...styleTheme.myButton,
  },
}));

const Rightbar: NextPage = () => {
  const classes = useStyles();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App with Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button
        variant="contained"
        className={classes.button}
        size="large"
        startIcon={<SendIcon />}>
        Hello World
      </Button>
    </div>
  );
};
export default Rightbar;
